
export NDK_VERSION=21.3.6528147
export ANDROID_NDK=${HOME}/Android/Sdk/ndk/${NDK_VERSION}
export JAVA_PACKAGE_PATH=scanner-jni/src/main/java/com/github/dawidkski/scanner/jni
BUILD_DIR=build-cmake

## Clean previous build
rm -rf ${BUILD_DIR}

## Run CMake and execute build
cmake -B ${BUILD_DIR} -S . \
 -DANDROID=ON \
 -Wno-dev
cd ${BUILD_DIR} && make
cd ..

## Copy shared libs into gradle project
libs_target=scanner-jni/src/main/jniLibs/arm64-v8a/
mkdir -p ${libs_target}
cp -r ${BUILD_DIR}/lib/* ${libs_target}

## Copy generated by SWIG java classes into gradle project
mkdir -p ${JAVA_PACKAGE_PATH}
cp -r ${BUILD_DIR}/java/${JAVA_PACKAGE_PATH}/*.java ${JAVA_PACKAGE_PATH}/
