
export NDK_VERSION=21.3.6528147
export ANDROID_NDK=${HOME}/Android/Sdk/ndk/${NDK_VERSION}
export JAVA_PACKAGE_PATH=scanner-jni/src/main/java/com/github/dawidkski/scanner/jni

BUILD_DIR=build-cmake
rm -rf ${BUILD_DIR}

for platform in arm64-v8a armeabi-v7a x86 x86_64 ; do
  mkdir -p ${BUILD_DIR}/${platform}
  cmake -B ${BUILD_DIR}/${platform} -S . \
   -DANDROID=ON \
   -DSWIG=ON \
   -DHOST=OFF \
   -DPLATFORM=${platform} \
   -Wno-dev
  cd ${BUILD_DIR}/${platform} && make -j 10
  cd ../..

  # Copy shared libs into gradle project
  libs_target=scanner-jni/src/main/jniLibs/${platform}/
  mkdir -p ${libs_target}
  cp -r ${BUILD_DIR}/${platform}/bin/*.so ${libs_target}
done

# Copy generated by SWIG java classes into gradle project
mkdir -p ${JAVA_PACKAGE_PATH}
cp -r ${BUILD_DIR}/${platform}/java/${JAVA_PACKAGE_PATH}/*.java ${JAVA_PACKAGE_PATH}/
