/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.github.dawidkski.scanner.jni;

public class ScannerJNI {
    public final static native void drawContour(long jarg1);

    public final static native void softwareScanner(long jarg1, long jarg2);

    public final static native String hello();
}
