/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.github.dawidkski.scanner.jni;

public class Scanner {
    public static void drawContour(long inputPtr) {
        ScannerJNI.drawContour(inputPtr);
    }

    public static void softwareScanner(long inputPtr, long outputPtr) {
        ScannerJNI.softwareScanner(inputPtr, outputPtr);
    }

    public static String hello() {
        return ScannerJNI.hello();
    }

}
